"""RegulSense Package Initialization."""

from src.citation_engine import (
    CitationAuditReport,
    CitationEngine,
    CitationMetadataRecord,
    CitedAnswerOutput,
    ClaimVerificationDetail,
    run_citation_evaluation_suite,
)
from src.context_assembler import (
    AugmentedPrompt,
    ContextAssembler,
    InjectedChunk,
    SourceMarker,
    TokenBudgetLedger,
    TokenBudgetManager,
    TokenBudgetSpec,
    run_sample_augmented_prompt,
)
from src.grounded_generator import (
    AccuracyVerificationReport,
    BaselineGenerationOutput,
    GroundedGenerationOutput,
    GroundedGenerator,
    RetrievalComparisonReport,
    run_grounded_generation_suite,
)
from src.hallucination_guardrails import (
    GuardrailExecutionResult,
    GuardrailThresholdConfig,
    HallucinationGuardrail,
    RetrievalQualityAssessment,
    run_hallucination_guardrails_suite,
)
from src.rag_pipeline import (
    AssembledContext,
    GenerationResult,
    PipelineStageMetrics,
    QueryEmbedding,
    RAGPipeline,
    RAGResponse,
    RetrievedContextChunk,
    SourceCitation,
    assemble_context_stage,
    attribute_sources_stage,
    embed_query_stage,
    generate_answer_stage,
    retrieve_chunks_stage,
    run_sample_pipeline,
)

__all__ = [
    "AccuracyVerificationReport",
    "AssembledContext",
    "AugmentedPrompt",
    "BaselineGenerationOutput",
    "CitationAuditReport",
    "CitationEngine",
    "CitationMetadataRecord",
    "CitedAnswerOutput",
    "ClaimVerificationDetail",
    "ContextAssembler",
    "GenerationResult",
    "GroundedGenerationOutput",
    "GroundedGenerator",
    "GuardrailExecutionResult",
    "GuardrailThresholdConfig",
    "HallucinationGuardrail",
    "InjectedChunk",
    "PipelineStageMetrics",
    "QueryEmbedding",
    "RAGPipeline",
    "RAGResponse",
    "RetrievalComparisonReport",
    "RetrievalQualityAssessment",
    "RetrievedContextChunk",
    "SourceCitation",
    "SourceMarker",
    "TokenBudgetLedger",
    "TokenBudgetManager",
    "TokenBudgetSpec",
    "assemble_context_stage",
    "attribute_sources_stage",
    "embed_query_stage",
    "generate_answer_stage",
    "retrieve_chunks_stage",
    "run_citation_evaluation_suite",
    "run_grounded_generation_suite",
    "run_hallucination_guardrails_suite",
    "run_sample_augmented_prompt",
    "run_sample_pipeline",
]
